### ISSUE TITLE
usb1 instead of usb0

### ISSUE THREAD

**Issue by crossholo** [stooged/AppToUsb-50X#1]
For some reason my (refurbished) PS4 detects my external HDD as usb1, while something else (i don't know what though) as usb0 - as seen on the images provided with FTP.
Therefore, packages are transferred (even partially) to this non-existent usb0 instead of usb1.
In addition, apptousb.bin creates a apptousb into usb0/PS4 by itself, but since it's not a real usb, it fails in transferring packages.
Yes, I tried swapping usb port but this hasn't helped.
Any solution? Maybe just changing usb0 to usb1 in the code and then compile it again into .bin would help.
Thanks
<img width="259" alt="screen shot 2018-05-30 at 10 33 59 pm" src="https://user-images.githubusercontent.com/28362961/40748121-ad687be8-645f-11e8-8cbb-48c954410d79.png">
<img width="246" alt="screen shot 2018-05-30 at 10 33 50 pm" src="https://user-images.githubusercontent.com/28362961/40748122-ad821b84-645f-11e8-9fd7-3de0c976e348.png">
<img width="309" alt="screen shot 2018-05-30 at 10 33 21 pm" src="https://user-images.githubusercontent.com/28362961/40748124-ada05554-645f-11e8-81a7-f02a7874f089.png">

**Comment by stooged** [comment]
make sure you don't have multiple partitions on the hdd.

looking in the usb0 folder there you have run the dumper payload and you have the folders -app and -patch which the dumper creates.
having those folders and the ps4 folder created you must have something acting as usb0.

if you have used that hdd as a windows drive or other operating system you will need to clean the partition table on the drive and make a new single partition formatted to exfat.
google "diskpart" and look for a tutorial on how to "clean" the partition table.

**Comment by crossholo** [comment]
apparently mac os x when creating  GUID partition creates an invisible 200mb partition too. formatting the hard disk with other ways helped it work again. thanks.
